Backend/UtxoCoin: introduce jsonrpc optional field
Otherwise the previous commit fixing a bug breaks the whole
protocol communication with regards of successful queries.
The exception was this when running the tests:

```
System.AggregateException: One or more errors occurred. (Operation canceled)
 ---> System.Net.Sockets.SocketException (89): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
   at System.Net.Sockets.TcpListener.<AcceptTcpClientAsync>g__WaitAndWrap|32_0(ValueTask`1 task)
   --- End of inner exception stack trace ---
  Failed End2End test of a correct interaction returning balance successfully [72 ms]
  Error Message:
   GWallet.Backend.UtxoCoin.ElectrumServerReturningImproperJsonResponseException : Failed deserializing JSON response '{"id":0,"jsonrpc":"2.0","result":["Fulcrum 2.1.1","1.4"]}' to type 'GWallet.Backend.UtxoCoin.ServerVersionResult'
  ----> Newtonsoft.Json.JsonSerializationException : Could not find member 'jsonrpc' on object of type 'ServerVersionResult'. Path 'jsonrpc', line 1, position 23.
  Stack Trace:
     at GWallet.Backend.UtxoCoin.StratumClient.DeserializeInternal[T](String result) in /Users/runner/work/geewallet/geewallet/src/GWallet.Backend/UtxoCoin/StratumClient.fs:line 202
   at GWallet.Backend.UtxoCoin.StratumClient.Deserialize[T](String result) in /Users/runner/work/geewallet/geewallet/src/GWallet.Backend/UtxoCoin/StratumClient.fs:line 217
   at <StartupCode$GWallet-Backend>.$StratumClient.Request@144-4.Invoke(Unit unitVar) in /Users/runner/work/geewallet/geewallet/src/GWallet.Backend/UtxoCoin/StratumClient.fs:line 144
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in /Users/runner/work/1/s/src/fsharp/src/FSharp.Core/async.fs:line 509
   at <StartupCode$GWallet-Backend>.$StratumClient.Request@143-24.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$GWallet-Backend>.$StratumClient.Request@139-28.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$GWallet-Backend>.$JsonRpcTcpClient.Request@94-3.Invoke(AsyncActivation`1 ctxt)
   at Fsdk.FSharpUtil.WithTimeout@213-2.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in /Users/runner/work/1/s/src/fsharp/src/FSharp.Core/async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in /Users/runner/work/1/s/src/fsharp/src/FSharp.Core/async.fs:line 453
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in /Users/runner/work/1/s/src/fsharp/src/FSharp.Core/async.fs:line 1138
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in /Users/runner/work/1/s/src/fsharp/src/FSharp.Core/async.fs:line 1165
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in /Users/runner/work/1/s/src/fsharp/src/FSharp.Core/async.fs:line 1514
   at GWallet.Backend.Tests.StratumParsing.End2End test of a correct interaction returning balance successfully() in /Users/runner/work/geewallet/geewallet/src/GWallet.Backend.Tests/StratumParsing.fs:line 172
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
--JsonSerializationException
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GWallet.Backend.UtxoCoin.StratumClient.DeserializeInternal[T](String result) in /Users/runner/work/geewallet/geewallet/src/GWallet.Backend/UtxoCoin/StratumClient.fs:line 193
  Standard Error Messages:
 Server Error: System.AggregateException: One or more errors occurred. (Operation canceled)
  ---> System.Net.Sockets.SocketException (89): Operation canceled
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token)
    at System.Net.Sockets.TcpListener.<AcceptTcpClientAsync>g__WaitAndWrap|32_0(ValueTask`1 task)
    --- End of inner exception stack trace ---
Failed!  - Failed:     1, Passed:   148, Skipped:     6, Total:   155, Duration: 53 s - GWallet.Backend.Tests.dll (net6.0)
```